---
title: 'Bios 6301: Assignment 5'
output: pdf_document
---

*Due Tuesday, 10 November, 1:00 PM*

$5^{n=day}$ points taken off for each day late.

50 points total.

Submit a single knitr file (named `homework5.rmd`), along with a valid PDF output file. Inside the file, clearly indicate which parts of your responses go with which problems (you may use the original homework document as a template). Add your name as `author` to the file's metadata section. Raw R code/output or word processor files are not acceptable.

Failure to name file `homework5.rmd` or include author name may result in 5 points taken off.

### Question 1 ###

**20 points**

Import the HAART dataset (`haart.csv`) from the GitHub repository into R, and perform the following manipulations:

1. Convert date columns into a usable (for analysis) format.
2. Create an indicator variable (one which takes the values 0 or 1 only) to represent death within 1 year of the initial visit.
3. Use the `init.date`, `last visit` and `death.date` to calculate a followup time, which is the difference between the first and either the last visit or a death event (whichever comes first). If these times are longer than 1 year, censor them.
4. Create another indicator variable representing loss to followup; that is, if their status 1 year after the first visit was unknown.
5. Recall our work in class, which separated the `init.reg` field into a set of indicator variables, one for each unique drug. Create these fields and append them to the database as new columns.
6. The dataset `haart2.csv` contains a few additional observations for the same study. Import these and append them to your master dataset (if you were smart about how you coded the previous steps, cleaning the additional observations should be easy!).

### Question 2 ###

**20 points**

Code a function that does golden section search, and use this function to find all of the global maxima on the following function:

$$f(x) = \left\{
  \begin{array}{ll}0 & \text{if } x=0 \\
  |x| \log\left(\frac{|x|}{2}\right)e^{-|x|} & \text{otherwise}
  \end{array}
\right.
$$

on the interval [-10, 10].

To get an idea of what the function looks like, it might be helpful to plot it.

### Question 3 ###

**10 points**

Obtain the code for using Newton's Method to estimate logistic regression parameters (`logistic.r`) and modify it to predict `death` from `weight`, `hemoglobin` and `cd4baseline` in the HAART dataset. Use complete cases only. Report the estimates for each parameter, including the intercept.

Note: The original script `logistic_debug.r` is in the exercises folder.  It needs modification, specifically, the logistic function should be defined:

```{r}
logistic <- function(x) 1 / (1 + exp(-x))
```

### Question 4 ###

**5 bonus points**

Import the `addr.txt` file from the GitHub repository.  This file contains a listing of names and addresses (thanks google).  Parse each line to create a data.frame with the following columns: lastname, firstname, streetno, streetname, city, state, zip.  Keep middle initials or abbreviated names in the firstname column.  Print out the entire data.frame.
