---
title: 'Bios 6301: Assignment 3'
output: pdf_document
---

*Due Thursday, 27 September, 1:00 PM*

50 points total.

$5^{n=day}$ points taken off for each day late.

### Question 1 ###

**15 points**

Write a simulation to calculate the power for the following study
design.  The study has two variables, treatment group and outcome.
There are two treatment groups (0, 1) and they should be assigned
randomly with equal probability.  The outcome should be a random normal
variable with a mean of 60 and standard deviation of 20.  If a patient
is in the treatment group, add 5 to the outcome.  5 is the true
treatment effect.  Create a linear model for the outcome by the
treatment group, and extract the p-value (hint: see assigment1).
Test if the p-value is less than or equal to the alpha level, which
should be set to 0.05.

Repeat this procedure 1000 times. The power is calculated by finding
the percentage of times the p-value is less than or equal to the alpha
level.  Use the `set.seed` command so that the professor can reproduce
your results.

1. Find the power when the sample size is 100 patients. (10 points)

1. Find the power when the sample size is 1000 patients. (5 points)

### Question 2 ###

**15 points**

Obtain a copy of the [football-values lecture](https://github.com/couthcommander/football-values).
Save the `2018/proj_wr18.csv` file in your working directory.  Read
in the data set and remove the first two columns.

1. Show the correlation matrix of this data set. (3 points)

1. Generate a data set with 30 rows that has a similar correlation
structure.  Repeat the procedure 10,000 times and return the mean
correlation matrix. (10 points)

1. Generate a data set with 30 rows that has the exact correlation
structure as the original data set. (2 points)
